### ISSUE TITLE
will it work for third order categorical features interaction

### ISSUE THREAD

**Issue by Sandy4321** [yandili/FM-BPR#1]
Great code, thanks !

Plese help to understand
1
will it work for third order categorical features interaction ?
2
will it run on Windows computer ?

3
will it work for sparse data ?

**Comment by yandili** [comment]
Hi Sandy, thanks for the comments! 

The project is obsolete, I won't recommend use it for any kind of training. 

The ideas in the code still applies, but you need to search for other code implemented in Deep Learning frameworks, like in "DeepFM/FM", for the FM part, and "Contrastive learning/Triplet loss" for the BPR part, and combine them.

**Comment by yandili** [comment]
To answer to your questions,
1, FM only models second order interactions, between each user and item features. If you have a third dimension, let's say context, e.g., days of the week, I think you can model it like 

$$\sum{Vu\*Vi} + \sum{Vu\*Vc} + \sum{Vc\*Vi}$$

for an approximation, where \* means element-wise product between two embeddings.

If you do need a full interaction, then it is 
$$<user, item, context>= \sum{Vu\*Vi\*Vc}$$

However, these are extensions to plain FM, you have to write your own code, probably in PyTorch to make it easy.

2, I think so.
3, Yes, FM works great on sparse data, it generalizes well.
